volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-sports_events}
      - DB_USERNAME=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASS:-123}
    depends_on:
      - db
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../backend:/work/backend
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:latest
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-store:/var/lib/mysql
      - ../backend/mysql-init-scripts:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-123} # Пароль для root
      MYSQL_DATABASE: ${DB_NAME:-sports_events} # База данных по умолчанию
      # MYSQL_PASSWORD: ${DB_PASS}
      # MYSQL_USER: ${DB_USER}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: php_course
    restart: always
    networks:
      - backend

networks:
  backend:
